# -*- coding: utf-8 -*-
"""Analisis de datos combinados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kcrjZ5HGVE713TLz8CY38cEDpvymhKN

##**Punto 4**
Consideramos que la variable “Familiares” es muy útil, ya que representa el tamaño de la familia que acompañaba a cada pasajero en el barco. En el caso del Titanic, creemos que el tamaño de la familia pudo influir en la probabilidad de sobrevivir. Por ejemplo:


*   Familias pequeñas (1–3 miembros): podían ayudarse mutuamente para sobrevivir
*  Personas solas (0 familiares): posiblemente no contaban con apoyo durante la evacuación
*  Familias muy grandes (4 o más integrantes): podían tener más dificultades para permanecer juntas y evacuar con rapidez.
"""

# Nueva variable 'Familiares' en train
train["Familiares"] = train["SibSp"] + train["Parch"]

print("Primeros valores de la nueva variable 'Familiares':")
display(train[["SibSp", "Parch", "Familiares"]].head())

# Nueva variable 'Familiares' en test
test["Familiares"] = test["SibSp"] + test["Parch"]

print("Primeros valores de la nueva variable 'Familiares':")
display(test[["SibSp", "Parch", "Familiares"]].head())

"""##**Punto 5**"""

# Aqui agregamos una columna llamada 'Origen' para indicar en el dataframe nuevo de donde proviene cada fila
train["Origen"] = "train"
test["Origen"] = "test"

# Aqui agregamos la columna 'Survived' rellena de valores nulos para evitar errores y mantener la misma estructura de las columnas
test["Survived"] = None

print("\nDataFrames con la nueva columna 'origen':")
print("\nTrain:")
display(train.head(2))
print("\nTest:")
display(test.head(2))

# Unimos los DataFrames verticalmente con la función concat y usamos la función ignore_index para reasignar los índices y no hayan índices duplicados
data_total = pd.concat([train, test], axis=0, ignore_index=True)

print("\nDataFrame combinado (train + test) con columna 'origen':")
print("\nPrimeras 5 filas:")
display(data_total.head())
print("\nUltimas 5 filas:")
display(data_total.tail())

"""##**Punto 6**
Discusión grupal:
*  Como grupo concluimos que las variables numéricas de ambos conjuntos (train y test) presentan medias, desviaciones y rangos muy similares. Esto significa que los dos provienen de la misma población y no hay diferencias significativas entre ellos. En general, consideramos que el conjunto de prueba es representativo y adecuado para evaluar correctamente el modelo entrenado.
"""

# Estadísticas del nuevo DataFrame
print("\nEstadísticas DataFrame completo (data_total):")
display(data_total.describe(include='all'))

"""##**Punto 7**
Como grupo concluimos que los datos faltantes tienen distintos significados según la variable. En Age y Fare, representan información que no fue registrada en su momento. En Cabin, los valores nulos indican que muchos pasajeros no tenían cabina asignada, especialmente los de tercera clase. En Embarked, los faltantes se deben a pequeños errores de registro histórico. Finalmente, en Survived, la ausencia de datos en el conjunto de prueba es intencional, ya que es la variable que el modelo debe predecir
"""