# -*- coding: utf-8 -*-
"""Analisis de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzUmX9-pPskZBsJfgQ6aLVrtKgAFj_Tl

##**Punto 1**


*   Se cargaron los archivos CSV en un dataframe distinto
*   Con la funcion **.shape** se explora el dataframe y esto nos muestras las dimensiones, es decir cuantas filas y columnas tiene
"""

print("\nDataFrame TRAIN")
train = pd.read_csv("train.csv")
print("Test shape:", train.shape)
train.head()

print("\nDataFrame TEST")
test = pd.read_csv("test.csv")
print("Test shape:", test.shape)
test.head()

"""##**Punto 2**
*Descripción de las variables del DataFrame TRAIN*


| Variable    | Tipo de dato                 | Descripción |
|--------------|-----------------------------|--------------|
| PassengerId  | Entero                      | Identificador único asignado a cada pasajero en el dataset. |
| Survived     | Binaria (0 = No, 1 = Sí)    | Indica si el pasajero sobrevivió al naufragio del Titanic. Es la variable objetivo (*target*). |
| Pclass       | Categórica (1, 2, 3)        | Clase del boleto del pasajero. Representa el nivel socioeconómico: 1 = alta, 2 = media, 3 = baja. |
| Name         | Texto                       | Nombre completo del pasajero, incluye título social (Mr., Mrs., Miss., etc.). |
| Sex          | Categórica (male/female)    | Género del pasajero. |
| Age          | Numérica (decimal)          | Edad del pasajero en años. Algunos valores están ausentes. |
| SibSp        | Entera                      | Número de hermanos o esposas(os) que viajaban junto al pasajero. |
| Parch        | Entera                      | Número de padres o hijos que acompañaban al pasajero. |
| Ticket       | Texto                       | Número o código del boleto adquirido. |
| Fare         | Numérica (decimal)          | Precio del boleto pagado por el pasajero. |
| Cabin        | Texto                       | Código de la cabina asignada. Muchos pasajeros no tienen esta información registrada. |
| Embarked     | Categórica (C, Q, S)        | Puerto donde el pasajero abordó el barco: C = Cherbourg, Q = Queenstown, S = Southampton. |
| Familiares   | Entera                      | Variable creada sumando **SibSp + Parch**. Representa el total de familiares que viajaban con el pasajero. |



*Descripción de las variables del DataFrame TEST*

| **Variable** | **Tipo de dato** | **Descripción** |
|---------------|------------------|-----------------|
| PassengerId | Entera | Identificador único de cada pasajero en el conjunto de prueba. |
| Pclass | Categórica (1, 2, 3) | Clase del boleto del pasajero. Indica el nivel socioeconómico. |
| Name | Texto | Nombre completo del pasajero, con su título social. |
| Sex | Categórica (male/female) | Género del pasajero. |
| Age | Numérica | Edad en años. Puede contener valores faltantes. |
| SibSp | Entera | Número de hermanos o esposas(os) a bordo. |
| Parch | Entera | Número de padres o hijos a bordo. |
| Ticket | Texto | Número o código del boleto. |
| Fare | Numérica | Tarifa pagada por el pasajero. |
| Cabin | Texto | Cabina asignada (dato incompleto en la mayoría de registros). |
| Embarked | Categórica (C, Q, S) | Puerto de embarque. |
| Familiares | Entera | Variable calculada como **SibSp + Parch**, muestra el número total de familiares en el barco. |

##**Punto 3**
La comparación de DataFrames muestra que:

*  Ambos dataframes comparten variables como Pclass, Sex, Age, SibSp, Parch, Fare y Embarked

*   Solo el conjunto train tiene Survived que corresponde a la variable objetivo, indicando si el pasajero sobrevivió o no

*   En las estadísticas numéricas, se puede observar que las variables tienen rangos similares en ambos conjuntos
"""

print("Estadísticas del DataFrame TRAIN")
print(train.describe(include='all'))
print("\nInformación general de TRAIN:")
print(train.info()) # obtenemos info de train...

print("\nEstadísticas del DataFrame TEST")
print(test.describe(include='all'))
print("\nInformación general de TEST:")
print(test.info()) #obtenemos info de test

# Columnas comunes y diferentes
print("\nColumnas comunes:", list(set(train.columns) & set(test.columns)))
print("Columnas solo en train:", list(set(train.columns) - set(test.columns)))
print("Columnas solo en test:", list(set(test.columns) - set(train.columns)))

# Valores nulos
print("\nValores nulos en train:")
print(train.isnull().sum())
print("\nValores nulos en test:")
print(test.isnull().sum())

"""##**Punto 4**
Consideramos que la variable “Familiares” es muy útil, ya que representa el tamaño de la familia que acompañaba a cada pasajero en el barco. En el caso del Titanic, creemos que el tamaño de la familia pudo influir en la probabilidad de sobrevivir. Por ejemplo:


*   Familias pequeñas (1–3 miembros): podían ayudarse mutuamente para sobrevivir
*  Personas solas (0 familiares): posiblemente no contaban con apoyo durante la evacuación
*  Familias muy grandes (4 o más integrantes): podían tener más dificultades para permanecer juntas y evacuar con rapidez.




"""

# Nueva variable 'Familiares' en train
train["Familiares"] = train["SibSp"] + train["Parch"]

print("Primeros valores de la nueva variable 'Familiares':")
display(train[["SibSp", "Parch", "Familiares"]].head())

# Nueva variable 'Familiares' en test
test["Familiares"] = test["SibSp"] + test["Parch"]

print("Primeros valores de la nueva variable 'Familiares':")
display(test[["SibSp", "Parch", "Familiares"]].head())

"""##**Punto 5**"""

# Aqui agregamos una columna llamada 'Origen' para indicar en el dataframe nuevo de donde proviene cada fila
train["Origen"] = "train"
test["Origen"] = "test"

# Aqui agregamos la columna 'Survived' rellena de valores nulos para evitar errores y mantener la misma estructura de las columnas
test["Survived"] = None

print("\nDataFrames con la nueva columna 'origen':")
print("\nTrain:")
display(train.head(2))
print("\nTest:")
display(test.head(2))

# Unimos los DataFrames verticalmente con la función concat y usamos la función ignore_index para reasignar los índices y no hayan índices duplicados
data_total = pd.concat([train, test], axis=0, ignore_index=True)

print("\nDataFrame combinado (train + test) con columna 'origen':")
print("\nPrimeras 5 filas:")
display(data_total.head())
print("\nUltimas 5 filas:")
display(data_total.tail())

"""##**Punto 6**
Discusión grupal:
*  Como grupo concluimos que las variables numéricas de ambos conjuntos (train y test) presentan medias, desviaciones y rangos muy similares. Esto significa que los dos provienen de la misma población y no hay diferencias significativas entre ellos. En general, consideramos que el conjunto de prueba es representativo y adecuado para evaluar correctamente el modelo entrenado.
"""

# Estadísticas del nuevo DataFrame
print("\nEstadísticas DataFrame completo (data_total):")
display(data_total.describe(include='all'))

"""##**Punto 7**
Como grupo concluimos que los datos faltantes tienen distintos significados según la variable. En Age y Fare, representan información que no fue registrada en su momento. En Cabin, los valores nulos indican que muchos pasajeros no tenían cabina asignada, especialmente los de tercera clase. En Embarked, los faltantes se deben a pequeños errores de registro histórico. Finalmente, en Survived, la ausencia de datos en el conjunto de prueba es intencional, ya que es la variable que el modelo debe predecir

##**Punto 8**
*Respondimos a cada pregunta con los resultados que arroja el siguiente codigo*
"""

# (a) Edad promedio de todos los pasajeros (train + test)
edad_promedio = data_total["Age"].mean()
print(f"(a) Edad promedio de los pasajeros: {edad_promedio:.2f} años")

# (b) Pasajeros que sobrevivieron y murieron
sobrevivieron_total = data_total["Survived"].sum()
murieron_total = data_total["Survived"].count() - sobrevivieron_total
print(f"(b) Sobrevivieron: {int(sobrevivieron_total)} | Murieron: {int(murieron_total)}")

# (c) Tarifa promedio pagada por los pasajeros de primera clase
tarifa_promedio = data_total[data_total["Pclass"] == 1]["Fare"].mean()
print(f"(c) Tarifa promedio de primera clase: {tarifa_promedio:.2f}")

# (d) Pasajeros que viajaron con al menos un familiar a bordo
con_familia = data_total[data_total["Familiares"] > 0].shape[0]
print(f"(d) Pasajeros con familiares a bordo: {con_familia}")

# (e) Edad más joven y más vieja
edad_min = data_total["Age"].min()
edad_max = data_total["Age"].max()
print(f"(e) Edad más joven: {edad_min} años | Edad más vieja: {edad_max} años")

# (f) Pasajeros por puerto de embarque
print("(f) Pasajeros por puerto de embarque:")
display(data_total["Embarked"].value_counts())

# (g) Pasajeros solos y con familiares
solos = data_total[data_total["Familiares"] == 0].shape[0]
con_familia = data_total[data_total["Familiares"] > 0].shape[0]
print(f"(g) Viajaron solos: {solos} | Viajaron con familiares: {con_familia}")

"""##**Punto 9**
**(a)** Sí, como grupo observamos que sobrevivieron más mujeres que hombres, y proporcionalmente las mujeres también tuvieron una tasa de supervivencia mucho mayor

**(b)** Concluimos que sobrevivieron más niños que hombres adultos, y proporcionalmente los niños también tuvieron una mayor probabilidad de sobrevivir

**(c)** Notamos que los pasajeros menores de 10 años sobrevivieron más que los de otros grupos etarios, mientras que los mayores de 50 tuvieron una tasa de supervivencia más baja

**(d)** Vimos que la mayor cantidad de sobrevivientes partió de Southampton, aunque proporcionalmente los pasajeros de los otros puertos (Cherbourg y Queenstown) presentaron tasas de supervivencia más altas

**(e)** Finalmente, observamos que los pasajeros de primera clase sobrevivieron más, y proporcionalmente también tuvieron la mayor tasa de supervivencia frente a las demás clases
"""

# (a) Mujeres vs hombres
print("(a) Supervivencia por sexo:")
tabla_sexo = data_total.groupby("Sex")["Survived"].agg(['sum','count','mean'])
display(tabla_sexo)

# (b) Niños (<18 años) vs hombres adultos (>=18 y sexo masculino)
print("(b) Supervivencia de niños vs hombres adultos:")
niños = data_total[(data_total["Age"] < 18)]
hombres_adultos = data_total[(data_total["Age"] >= 18) & (data_total["Sex"] == "male")]

print(f"Niños que sobrevivieron: {niños['Survived'].sum()} de {niños['Survived'].count()}  - Promedio: {niños['Survived'].mean():.2f}")
print(f"Hombres adultos que sobrevivieron: {hombres_adultos['Survived'].sum()} de {hombres_adultos['Survived'].count()}  - Promedio: {hombres_adultos['Survived'].mean():.2f}")

# (c) Pasajeros con edad >50 o <10 años
print("\n(c) Supervivencia en mayores de 50 y menores de 10 años:")
grupo_mayores = data_total[data_total["Age"] > 50]
grupo_menores = data_total[data_total["Age"] < 10]
grupo_intermedio = data_total[(data_total["Age"] >= 10) & (data_total["Age"] <= 50)]

print(f"Mayores de 50: {grupo_mayores['Survived'].mean():.2f}")
print(f"Menores de 10: {grupo_menores['Survived'].mean():.2f}")
print(f"Entre 10 y 50: {grupo_intermedio['Survived'].mean():.2f}")

# (d) Puerto de embarque
print("\n(d) Supervivencia por puerto de embarque:")
tabla_emb = data_total.groupby("Embarked")["Survived"].agg(['sum','count','mean'])
display(tabla_emb)

# (e) Clase del boleto
print("\n(e) Supervivencia por clase (Pclass):")
tabla_clase = data_total.groupby("Pclass")["Survived"].agg(['sum','count','mean'])
display(tabla_clase)

"""##**Punto 10**

"""

# Clasificamos de los pasajeros en grupos familiares
def clasificar_familia(x):
    if x == 0:
        return "Grupo 1: Sin familiares"
    elif 1 <= x <= 3:
        return "Grupo 2: Familias pequeñas"
    else:
        return "Grupo 3: Familias grandes"

# Creamos la nueva columna 'Grupo_familiar'
data_total["Grupo_familiar"] = data_total["Familiares"].apply(clasificar_familia)

print("Clasificación de pasajeros por tamaño de familia:")
display(data_total[["Familiares", "Grupo_familiar"]].head(10))

# Distribución de cabinas (solo las que sí están registradas)
print("\nDistribución de cabinas registradas por grupo familiar:")
tabla_cabinas = data_total.groupby("Grupo_familiar")["Cabin"].value_counts()
display(tabla_cabinas)

"""##**Punto 11**
Como grupo concluimos que el sexo y la posesión de cabina influyeron fuertemente en la supervivencia. Las mujeres y los niños, especialmente quienes tenían cabina, presentaron las tasas más altas de supervivencia, mientras que los hombres adultos sin cabina fueron el grupo más afectado. En general, la cabina y el sexo se destacan como factores determinantes en las probabilidades de sobrevivir.
"""

# Creamos la nueva variable 'Grupo_etario'
def clasificar_edad(edad):
    if pd.isnull(edad):
        return None
    elif edad < 10:
        return "Niño"
    elif 18 <= edad <= 49:
        return "Adulto"
    elif edad >= 50:
        return "Mayor"
    else:
        return "Otro"  # Aqui son edades entre 10 y 17 años

data_total["Grupo_etario"] = data_total["Age"].apply(clasificar_edad)

# Creamos columna booleana para identificar si tiene cabina
data_total["Tiene_cabina"] = data_total["Cabin"].notnull()

# Agrupamos por grupo etario, sexo y cabina, calculando supervivencia
tabla_proporciones = data_total.groupby(["Grupo_etario", "Sex", "Tiene_cabina"])["Survived"].agg(["sum", "count", "mean"])

print("Proporción de supervivencia por grupo etario, sexo y cabina:")
display(tabla_proporciones)

"""##**Punto 13**
*Creamos la siguiente tabla para responder a la pregunta*

Como grupo concluimos que las mujeres, especialmente las de clases altas y con cabina, fueron quienes tuvieron más probabilidades de sobrevivir. En cambio, los hombres adultos de clases bajas sin cabina fueron los más vulnerables. Esto refleja que factores como el sexo, la clase social y el acceso a cabina influyeron fuertemente en las posibilidades de supervivencia en el Titanic
"""

# Filtramos solo las filas donde Survived sea 0 o 1 (del train)
mask = data_total["Survived"].isin([0,1])
df = data_total.loc[mask]

# Calculamos la tasa de supervivencia por sexo, clase, cabina y grupo etario
tabla = (df.groupby(["Sex", "Pclass", "Tiene_cabina", "Grupo_etario"])["Survived"].mean().reset_index().sort_values("Survived", ascending=False))

# Mostramos los 20 grupos con mayor supervivencia
display(tabla.head(20))