# -*- coding: utf-8 -*-
"""Analisis de datos_Santiago.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuXktqK9tGSGHSJ0FbNOQ4nguv4fxbj9

##**Punto 2**
*Descripción de las variables del DataFrame TRAIN*


| Variable    | Tipo de dato                 | Descripción |
|--------------|-----------------------------|--------------|
| PassengerId  | Entero                      | Identificador único asignado a cada pasajero en el dataset. |
| Survived     | Binaria (0 = No, 1 = Sí)    | Indica si el pasajero sobrevivió al naufragio del Titanic. Es la variable objetivo (*target*). |
| Pclass       | Categórica (1, 2, 3)        | Clase del boleto del pasajero. Representa el nivel socioeconómico: 1 = alta, 2 = media, 3 = baja. |
| Name         | Texto                       | Nombre completo del pasajero, incluye título social (Mr., Mrs., Miss., etc.). |
| Sex          | Categórica (male/female)    | Género del pasajero. |
| Age          | Numérica (decimal)          | Edad del pasajero en años. Algunos valores están ausentes. |
| SibSp        | Entera                      | Número de hermanos o esposas(os) que viajaban junto al pasajero. |
| Parch        | Entera                      | Número de padres o hijos que acompañaban al pasajero. |
| Ticket       | Texto                       | Número o código del boleto adquirido. |
| Fare         | Numérica (decimal)          | Precio del boleto pagado por el pasajero. |
| Cabin        | Texto                       | Código de la cabina asignada. Muchos pasajeros no tienen esta información registrada. |
| Embarked     | Categórica (C, Q, S)        | Puerto donde el pasajero abordó el barco: C = Cherbourg, Q = Queenstown, S = Southampton. |
| Familiares   | Entera                      | Variable creada sumando **SibSp + Parch**. Representa el total de familiares que viajaban con el pasajero. |



*Descripción de las variables del DataFrame TEST*

| **Variable** | **Tipo de dato** | **Descripción** |
|---------------|------------------|-----------------|
| PassengerId | Entera | Identificador único de cada pasajero en el conjunto de prueba. |
| Pclass | Categórica (1, 2, 3) | Clase del boleto del pasajero. Indica el nivel socioeconómico. |
| Name | Texto | Nombre completo del pasajero, con su título social. |
| Sex | Categórica (male/female) | Género del pasajero. |
| Age | Numérica | Edad en años. Puede contener valores faltantes. |
| SibSp | Entera | Número de hermanos o esposas(os) a bordo. |
| Parch | Entera | Número de padres o hijos a bordo. |
| Ticket | Texto | Número o código del boleto. |
| Fare | Numérica | Tarifa pagada por el pasajero. |
| Cabin | Texto | Cabina asignada (dato incompleto en la mayoría de registros). |
| Embarked | Categórica (C, Q, S) | Puerto de embarque. |
| Familiares | Entera | Variable calculada como **SibSp + Parch**, muestra el número total de familiares en el barco. |

##**Punto 3**
La comparación de DataFrames muestra que:

*  Ambos dataframes comparten variables como Pclass, Sex, Age, SibSp, Parch, Fare y Embarked

*   Solo el conjunto train tiene Survived que corresponde a la variable objetivo, indicando si el pasajero sobrevivió o no

*   En las estadísticas numéricas, se puede observar que las variables tienen rangos similares en ambos conjuntos
"""

print("Estadísticas del DataFrame TRAIN")
print(train.describe(include='all'))
print("\nInformación general de TRAIN:")
print(train.info())

print("\nEstadísticas del DataFrame TEST")
print(test.describe(include='all'))
print("\nInformación general de TEST:")
print(test.info()) 

#Estadisticas del los datasets 

# Columnas comunes y diferentes
print("\nColumnas comunes:", list(set(train.columns) & set(test.columns)))
print("Columnas solo en train:", list(set(train.columns) - set(test.columns)))
print("Columnas solo en test:", list(set(test.columns) - set(train.columns)))

# Valores nulos
print("\nValores nulos en train:")
print(train.isnull().sum())
print("\nValores nulos en test:")
print(test.isnull().sum())