# -*- coding: utf-8 -*-
"""Carga de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJS6aTx87vGoen2QfpnqITnM2nlFIPNW

##**Proceso de importación del conjunto de datos del Titanic desde Kaggle**
"""

# Importamos la libreria pandas
import pandas as pd

# Configuramos el acceso a kaggle, para poder descargar los datos
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json #credenciales

# Descargamos el dataset
!kaggle competitions download -c titanic

# Descomprimimos el archivo ZIP descargado, extrayendo los archivos CSV
!unzip titanic.zip