# -*- coding: utf-8 -*-
"""Graficos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vs6SgRsn41tXjWAuDXmz3Bh1oqvC3Rcr

##**Punto 12. Gráficas**
"""

# Importamos la librería matplotlib para crear y mostrar las gráficas
import matplotlib.pyplot as plt

# Creamos un histograma para comparar la distribución de edades entre pasajeros que sobrevivieron y los que no
plt.figure(figsize=(8,5))
mask = data_total["Survived"].isin([0,1])
plt.hist(data_total.loc[mask & (data_total["Survived"]==0), "Age"].dropna(),
         bins=25, alpha=0.6, label="No sobrevivió", color="lightcoral")
plt.hist(data_total.loc[mask & (data_total["Survived"]==1), "Age"].dropna(),
         bins=25, alpha=0.6, label="Sobrevivió", color="skyblue")
plt.title("Distribución de la edad según supervivencia")
plt.xlabel("Edad")
plt.ylabel("Número de pasajeros")
plt.legend()
plt.tight_layout()
plt.show()

# Creamos un gráfico de barras para comparar la proporción de supervivencia entre mujeres y hombres
mask = data_total["Survived"].isin([0,1])
tabla_sexo = data_total.loc[mask].groupby("Sex")["Survived"].mean()
plt.bar(tabla_sexo.index, tabla_sexo.values, color=["lightcoral","skyblue"])
plt.title("Proporción de supervivencia por sexo")
plt.ylabel("Proporción de sobrevivientes")
plt.xlabel("Sexo")
plt.ylim(0,1)
plt.tight_layout()
plt.show()

# Creamos un gráfico de barras que muestra la proporción de supervivencia según el grupo etario y el sexo,
# comparando mujeres y hombres dentro de cada categoría de edad
mask = data_total["Survived"].isin([0,1]) & data_total["Grupo_etario"].notnull()
tabla_ge_sex = data_total.loc[mask].groupby(["Grupo_etario","Sex"])["Survived"].mean()

orden = ["Niño","Adulto","Mayor"]
sexos = ["female","male"]
vals_f = [tabla_ge_sex.get((g,"female"),0) for g in orden]
vals_m = [tabla_ge_sex.get((g,"male"),0) for g in orden]

x = range(len(orden))
w = 0.35
plt.figure(figsize=(9,6))
plt.bar([i-w/2 for i in x], vals_f, width=w, label="Mujeres", color="lightpink")
plt.bar([i+w/2 for i in x], vals_m, width=w, label="Hombres", color="steelblue")
plt.xticks(x, orden)
plt.ylim(0,1)
plt.ylabel("Proporción de sobrevivientes")
plt.title("Supervivencia por grupo etario y sexo")
plt.legend()
plt.tight_layout()
plt.show()

# Creamos un mapa de calor que muestra cómo cambia la supervivencia según el sexo y si el pasajero tenía o no cabina
mask = data_total["Survived"].isin([0,1])
cr = pd.crosstab([data_total.loc[mask,"Sex"],
                  data_total.loc[mask,"Tiene_cabina"]],
                 data_total.loc[mask,"Survived"],
                 normalize="index")

plt.imshow(cr, cmap="coolwarm", aspect="auto")
plt.xticks([0,1], ["No sobrevivió","Sí sobrevivió"])
plt.yticks(range(cr.shape[0]),
           [f"{idx[0]} | cabina={idx[1]}" for idx in cr.index])
for i in range(cr.shape[0]):
    for j in range(cr.shape[1]):
        plt.text(j, i, f"{cr.values[i,j]:.2f}", ha="center", va="center", color="white")
plt.title("Supervivencia por sexo y presencia de cabina")
plt.tight_layout()
plt.show()

"""##**Punto 13**
*Creamos la siguiente tabla para responder a la pregunta*

Como grupo concluimos que las mujeres, especialmente las de clases altas y con cabina, fueron quienes tuvieron más probabilidades de sobrevivir. En cambio, los hombres adultos de clases bajas sin cabina fueron los más vulnerables. Esto refleja que factores como el sexo, la clase social y el acceso a cabina influyeron fuertemente en las posibilidades de supervivencia en el Titanic
"""

# Filtramos solo las filas donde Survived sea 0 o 1 (del train)
mask = data_total["Survived"].isin([0,1])
df = data_total.loc[mask]

# Calculamos la tasa de supervivencia por sexo, clase, cabina y grupo etario
tabla = (df.groupby(["Sex", "Pclass", "Tiene_cabina", "Grupo_etario"])["Survived"].mean().reset_index().sort_values("Survived", ascending=False))

# Mostramos los 20 primeros grupos con mayor supervivencia
display(tabla.head(20))